PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/3df686e10f1d98ed064a9d18c8147138aad44108

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (abd2bb4eb738eef2007c43206a353ca38d4fdf6e)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...3df686e10f1d98ed064a9d18c8147138aad44108

3df686e10f (HEAD, origin/master) sim: berr() unknown relocation type
3ead7795b2 sim: Add loadable module definitions
7f1f930a7b Remove unneeded dependency on USB
1200c6d429 Using debug macros for memory card
1832172432 Fix wrong name for CONFIG_MMCSD_SPI
0b25b96759 net/netlink/netlink_route.c:  Fix a typo.
46ad645efc mm: Add a bunch of assertions
c1a32fb9dd compiler.h: clang actually has long long
1382ea5447 mm/: Coding style clean-up
3381ecb913 Remove CONFIG_BUILTIN_PROXY_STACKSIZE from README files

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/c5673957cc270d3e8d0b9fc4293cb0be56114592

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (abd2bb4eb738eef2007c43206a353ca38d4fdf6e)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...c5673957cc270d3e8d0b9fc4293cb0be56114592

c5673957 (HEAD -> master, origin/master) Remove unused BUILTIN_PROXY_STACKSIZE config
44b8c9c5 apps/examples/tcpblaster:  Fix compile errors in loopback mode.
539d0854 examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib